### ISSUE TITLE
Does this lib support connection pool?

### ISSUE THREAD

**Issue by IterableTrucks** [patrickpissurno/vredis#1]

**Comment by chovy** [comment]
i think this project is dead.

**Comment by patrickpissurno** [comment]
Answering the OP: _"Does this lib support connection pool?"_

Not at the moment. This is just a simple implementation of the Redis protocol, because at the time I wrote this, there was no Redis client for V. It could be enhanced to support connection pool and more advanced features, though. I just don't have time to do so at the moment.

**This project isn't dead.** 

However, as the V spec changed significantly, there are a lot of changes that have to be done in order for it to be compatible with the current version.

Even though I don't have time at the moment to learn about all the new changes and how to do the required work, this repo is still a nice open-source example on how to interface with the Redis protocol.

Feel free to open a PR with the required changes and I'll happily review it and accept it.
